version: '3.8'

services:
  order-service:
    container_name: order-service
    build:
      args:
        GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
      context: .
      dockerfile: Dockerfile
    image: order-service:latest
    command: ['node', './dist/src/main.js']
    env_file:
      - ./.env
    environment:
      DATABASE_CONNECTION_STRING: postgresql://postgres:postgres@postgres-12x:5432/order-service?schema=public
      NODE_ENV: development
    ports:
      - '3049:3049'
    depends_on:
      - postgres-12x

  postgres-12x:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-12x:/var/lib/postgresql/data:delegated
    ports:
      - '5434:5432'

volumes:
  postgres-12x:
